/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import clientdcd.ClientDCD;
import com.sun.org.apache.bcel.internal.generic.InstructionConstants;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author sragneau
 */
public class Accueil extends javax.swing.JFrame {

    /**
     * Creates new form Accueil
     */
    public Accueil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupOuiNon = new javax.swing.ButtonGroup();
        cbDcOui = new javax.swing.JRadioButton();
        cbDcNon = new javax.swing.JRadioButton();
        lblTitre = new javax.swing.JLabel();
        lblDc = new javax.swing.JLabel();
        tbxIdClient = new javax.swing.JTextField();
        lblIdClient = new javax.swing.JLabel();
        txbEnregistrer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion EXIT");
        setResizable(false);

        btnGroupOuiNon.add(cbDcOui);
        cbDcOui.setSelected(true);
        cbDcOui.setLabel("Oui");
        cbDcOui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDcOuiActionPerformed(evt);
            }
        });

        btnGroupOuiNon.add(cbDcNon);
        cbDcNon.setLabel("Non");
        cbDcNon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDcNonActionPerformed(evt);
            }
        });

        lblTitre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitre.setText("Gestion de l'exit Client");

        lblDc.setText("Décédé ?");

        lblIdClient.setText("id Client");

        txbEnregistrer.setText("Enregistrer");
        txbEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txbEnregistrerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbDcNon)
                    .addComponent(lblDc)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbDcOui)
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txbEnregistrer)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblIdClient)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tbxIdClient, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(lblTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(lblDc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDcOui)
                    .addComponent(tbxIdClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdClient))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbDcNon)
                .addGap(28, 28, 28)
                .addComponent(txbEnregistrer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbDcOuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDcOuiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDcOuiActionPerformed

    private void cbDcNonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDcNonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDcNonActionPerformed

    private void txbEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txbEnregistrerActionPerformed
        try {
            //Valeur par défaut
            boolean deces = true;
            if(cbDcNon.isSelected())
            {
                deces = false;
            }
            ClientDCD.deceder(tbxIdClient.getText(),deces);
        } catch (Exception ex) {
            Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txbEnregistrerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupOuiNon;
    private javax.swing.JRadioButton cbDcNon;
    private javax.swing.JRadioButton cbDcOui;
    private javax.swing.JLabel lblDc;
    private javax.swing.JLabel lblIdClient;
    private javax.swing.JLabel lblTitre;
    private javax.swing.JTextField tbxIdClient;
    private javax.swing.JButton txbEnregistrer;
    // End of variables declaration//GEN-END:variables
}
